server:
  port: 1235

# MYSQL
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: mysql
    url: jdbc:mysql://${SECURITY_DB_IP:localhost}:${SECURITY_DB_PORT:3307}/db_guarani_afv
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:guarani}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
  sql:
    init:
      mode: always


# SWAGGER
springdoc:
  api-docs:
    enabled: true
  show-actuator: true
