DELETE FROM ROLE_PERMISSION_RELATION_TABLE;
DELETE FROM PERMISSIONS;
DELETE FROM USER_ROLE_RELATION_TABLE;
DELETE FROM ROLES;
DELETE FROM ORDERS_DETAILS;
DELETE FROM ORDERS;
DELETE FROM PRODUCT;
DELETE FROM PRODUCT_CATEGORY;
DELETE FROM CUSTOMER;
DELETE FROM TYPE_PAYMENT;

-- Insert roles
INSERT INTO ROLES (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'ADMIN', NOW(), 'system', NOW(), 'system');

INSERT INTO ROLES (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'USER', NOW(), 'system', NOW(), 'system');

INSERT INTO ROLES (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'OPERATOR', NOW(), 'system', NOW(), 'system');

-- Insert permissions
INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'admin:create', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'admin:get', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'admin:update', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'admin:delete', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'user:get', NOW(), 'system', NOW(), 'system');

INSERT INTO PERMISSIONS (ID, NAME, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (UUID(), 'operator:get', NOW(), 'system', NOW(), 'system');

-- Insert role-permission relations
INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:create';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:get';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:update';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'ADMIN' AND p.NAME = 'admin:delete';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'USER' AND p.NAME = 'user:get';

INSERT INTO ROLE_PERMISSION_RELATION_TABLE (ROLE_ID, PERMISSION_ID)
SELECT r.ID, p.ID FROM ROLES r, PERMISSIONS p
WHERE r.NAME = 'OPERATOR' AND p.NAME = 'user:get';

INSERT INTO PRODUCT_CATEGORY (DESCRIPTION)
VALUES ('BEBIDAS');

INSERT INTO CUSTOMER (ID, NAME, ENDERECO, CREATED_AT, CREATED_BY )
VALUES (UUID(), 'PREFEITURA A', 'RUA LAFAIETE', NOW(), 'system');

INSERT INTO TYPE_PAYMENT (ID, DESCRIPTION, CREATED_AT, CREATED_BY)
VALUES (UUID(), 'CARTÃO DE CRÉDITO', NOW(), 'system');
INSERT INTO TYPE_PAYMENT (ID, DESCRIPTION, CREATED_AT, CREATED_BY)
VALUES (UUID(), 'BOLETO', NOW(), 'system');
INSERT INTO TYPE_PAYMENT (ID, DESCRIPTION, CREATED_AT, CREATED_BY)
VALUES (UUID(), 'TRANSFERÊNCIA BANCÁRIA', NOW(), 'system');

INSERT INTO ORDERS (ID, CREATED_AT, CREATED_BY, DISCOUNT, FREIGHT, STATUS, TOTAL, CUSTOMER_ID, TYPE_PAYMENT_ID, SUBTOTAL)
SELECT UUID(),  NOW(), 'system', 5, 10, 0, 185, ID, (SELECT MIN(ID) FROM TYPE_PAYMENT) TYPE_PAYMENT_ID, 100 FROM CUSTOMER;
INSERT INTO ORDERS (ID, CREATED_AT, CREATED_BY, DISCOUNT, FREIGHT, STATUS, TOTAL, CUSTOMER_ID, TYPE_PAYMENT_ID, SUBTOTAL)
SELECT UUID(),  NOW(), 'system', 15, 0, 1, 185, ID, (SELECT MIN(ID) FROM TYPE_PAYMENT) TYPE_PAYMENT_ID, 200 FROM CUSTOMER;
INSERT INTO ORDERS (ID, CREATED_AT, CREATED_BY, DISCOUNT, FREIGHT, STATUS, TOTAL, CUSTOMER_ID, TYPE_PAYMENT_ID, SUBTOTAL)
SELECT UUID(),  NOW(), 'system', 0,100, 2, 1400, ID, (SELECT MIN(ID) FROM TYPE_PAYMENT) TYPE_PAYMENT_ID, 1500 FROM CUSTOMER;
INSERT INTO ORDERS (ID, CREATED_AT, CREATED_BY, DISCOUNT, FREIGHT, STATUS, TOTAL, CUSTOMER_ID, TYPE_PAYMENT_ID, SUBTOTAL)
SELECT UUID(),  NOW(), 'system', 0,  0, 1, 1250, ID, (SELECT MIN(ID) FROM TYPE_PAYMENT) TYPE_PAYMENT_ID, 1250 FROM CUSTOMER;

